[build]
builder = "NIXPACKS"
buildCommand = "SKIP_MIGRATIONS=true npm install --omit=dev"

[deploy]
startCommand = "npm run migrate && npm start"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 3

[deploy.envs]
NODE_ENV = "production"
NPM_CONFIG_PRODUCTION = "true"